site_name: Phil Rice - Blog
site_url: https://philrice.me
theme:
  name: material
  palette:
    scheme: slate
    primary: orange
    accent: deep orange
  font:
    text: Roboto Mono
  icon:
    logo: material/code-tags

  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - blog:
      archive: true
      blog_dir: .
      blog_toc: true
  - search
  - tags
nav:
  - index.md
